#!/usr/bin/env bash
# Install nginx web server on my server and serve 'Hello World!' on homepage

apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service nginx start
