#!/usr/bin/env bash
# Install nginx web server on my server and serve 'Hello World!' on homepage

sudo apt-get update -y -qq && \
	sudo apt-get install nginx -y
sudo service nginx start
sudo ufw allow 'Nginx HTTP'
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www
echo -e "Hello World!" | dd status=none of=/var/www/html/index.nginx-debian.html
sudo service nginx restart
