#!/usr/bin/env bash
# Install nginx web server and redirect a page

apt-get update -y
apt-get upgrade -y
apt-get install nginx -y

chown -R "$USER":"$USER" /var/www/html
echo "Hello World!" > /var/www/html/index.nginx-debian.html

repl_str="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;"
sed -i "s/server_name _;/$repl_str/" /etc/nginx/sites-available/default

service nginx restart
