#!/usr/bin/env bash
# Create a script to install and configure HAProxy on lb-01 server
# Configure HAProxy to send traffic to web-01 and web-02 servers
# Distribute requests using a roundrobin algorithm
# Make sure that HAProxy can be managed via an init script
# Install and configure HAproxy on my lb-01 server.

sudo apt-get -y update
sudo apt-get -y install haproxy

server_config=\
"
frontend  endy4elect-frontend
        bind *:80
        mode http
        default_backend endy4elect-backend
backend endy4elect-backend
        balance roundrobin
        server 155105-web-01 54.90.55.169 check
        server 155105-web-02 100.25.24.147 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo service haproxy restart
